language: c
compiler: gcc
script: make
addons:
        apt:
                packages:
                        - check
                        - valgrind
after_success:
        - bash <(curl -s https://codecov.io/bash)
